//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfLapTopService
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanQuyen
    {
        public PhanQuyen()
        {
            this.NhanViens = new HashSet<NhanVien>();
        }
    
        public int MaPQ { get; set; }
        public string TenPQ { get; set; }
    
        public virtual ICollection<NhanVien> NhanViens { get; set; }
    }
}
