//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LapTopService.ServiceReferenceSanPham {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SanPham", Namespace="http://schemas.datacontract.org/2004/07/WcfLapTopService")]
    [System.SerializableAttribute()]
    public partial class SanPham : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LapTopService.ServiceReferenceSanPham.CT_DonHang[] CT_DonHangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LapTopService.ServiceReferenceSanPham.CT_PhieuNhap[] CT_PhieuNhapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HinhAnhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaLoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaSPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MoTaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LapTopService.ServiceReferenceSanPham.PhanLoai PhanLoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SoLuongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenSPField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LapTopService.ServiceReferenceSanPham.CT_DonHang[] CT_DonHang {
            get {
                return this.CT_DonHangField;
            }
            set {
                if ((object.ReferenceEquals(this.CT_DonHangField, value) != true)) {
                    this.CT_DonHangField = value;
                    this.RaisePropertyChanged("CT_DonHang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LapTopService.ServiceReferenceSanPham.CT_PhieuNhap[] CT_PhieuNhap {
            get {
                return this.CT_PhieuNhapField;
            }
            set {
                if ((object.ReferenceEquals(this.CT_PhieuNhapField, value) != true)) {
                    this.CT_PhieuNhapField = value;
                    this.RaisePropertyChanged("CT_PhieuNhap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Gia {
            get {
                return this.GiaField;
            }
            set {
                if ((this.GiaField.Equals(value) != true)) {
                    this.GiaField = value;
                    this.RaisePropertyChanged("Gia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HinhAnh {
            get {
                return this.HinhAnhField;
            }
            set {
                if ((object.ReferenceEquals(this.HinhAnhField, value) != true)) {
                    this.HinhAnhField = value;
                    this.RaisePropertyChanged("HinhAnh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaLoai {
            get {
                return this.MaLoaiField;
            }
            set {
                if ((this.MaLoaiField.Equals(value) != true)) {
                    this.MaLoaiField = value;
                    this.RaisePropertyChanged("MaLoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaSP {
            get {
                return this.MaSPField;
            }
            set {
                if ((this.MaSPField.Equals(value) != true)) {
                    this.MaSPField = value;
                    this.RaisePropertyChanged("MaSP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MoTa {
            get {
                return this.MoTaField;
            }
            set {
                if ((object.ReferenceEquals(this.MoTaField, value) != true)) {
                    this.MoTaField = value;
                    this.RaisePropertyChanged("MoTa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LapTopService.ServiceReferenceSanPham.PhanLoai PhanLoai {
            get {
                return this.PhanLoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.PhanLoaiField, value) != true)) {
                    this.PhanLoaiField = value;
                    this.RaisePropertyChanged("PhanLoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoLuong {
            get {
                return this.SoLuongField;
            }
            set {
                if ((this.SoLuongField.Equals(value) != true)) {
                    this.SoLuongField = value;
                    this.RaisePropertyChanged("SoLuong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenSP {
            get {
                return this.TenSPField;
            }
            set {
                if ((object.ReferenceEquals(this.TenSPField, value) != true)) {
                    this.TenSPField = value;
                    this.RaisePropertyChanged("TenSP");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhanLoai", Namespace="http://schemas.datacontract.org/2004/07/WcfLapTopService")]
    [System.SerializableAttribute()]
    public partial class PhanLoai : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaLoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LapTopService.ServiceReferenceSanPham.SanPham[] SanPhamsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenLoaiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaLoai {
            get {
                return this.MaLoaiField;
            }
            set {
                if ((this.MaLoaiField.Equals(value) != true)) {
                    this.MaLoaiField = value;
                    this.RaisePropertyChanged("MaLoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LapTopService.ServiceReferenceSanPham.SanPham[] SanPhams {
            get {
                return this.SanPhamsField;
            }
            set {
                if ((object.ReferenceEquals(this.SanPhamsField, value) != true)) {
                    this.SanPhamsField = value;
                    this.RaisePropertyChanged("SanPhams");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenLoai {
            get {
                return this.TenLoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.TenLoaiField, value) != true)) {
                    this.TenLoaiField = value;
                    this.RaisePropertyChanged("TenLoai");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CT_DonHang", Namespace="http://schemas.datacontract.org/2004/07/WcfLapTopService")]
    [System.SerializableAttribute()]
    public partial class CT_DonHang : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LapTopService.ServiceReferenceSanPham.DonHang DonHangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> GiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaDHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaSPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LapTopService.ServiceReferenceSanPham.SanPham SanPhamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SoLuongField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LapTopService.ServiceReferenceSanPham.DonHang DonHang {
            get {
                return this.DonHangField;
            }
            set {
                if ((object.ReferenceEquals(this.DonHangField, value) != true)) {
                    this.DonHangField = value;
                    this.RaisePropertyChanged("DonHang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Gia {
            get {
                return this.GiaField;
            }
            set {
                if ((this.GiaField.Equals(value) != true)) {
                    this.GiaField = value;
                    this.RaisePropertyChanged("Gia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaDH {
            get {
                return this.MaDHField;
            }
            set {
                if ((this.MaDHField.Equals(value) != true)) {
                    this.MaDHField = value;
                    this.RaisePropertyChanged("MaDH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaSP {
            get {
                return this.MaSPField;
            }
            set {
                if ((this.MaSPField.Equals(value) != true)) {
                    this.MaSPField = value;
                    this.RaisePropertyChanged("MaSP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LapTopService.ServiceReferenceSanPham.SanPham SanPham {
            get {
                return this.SanPhamField;
            }
            set {
                if ((object.ReferenceEquals(this.SanPhamField, value) != true)) {
                    this.SanPhamField = value;
                    this.RaisePropertyChanged("SanPham");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SoLuong {
            get {
                return this.SoLuongField;
            }
            set {
                if ((this.SoLuongField.Equals(value) != true)) {
                    this.SoLuongField = value;
                    this.RaisePropertyChanged("SoLuong");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CT_PhieuNhap", Namespace="http://schemas.datacontract.org/2004/07/WcfLapTopService")]
    [System.SerializableAttribute()]
    public partial class CT_PhieuNhap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> GiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaPNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaSPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LapTopService.ServiceReferenceSanPham.PhieuNhap PhieuNhapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LapTopService.ServiceReferenceSanPham.SanPham SanPhamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SoLuongField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Gia {
            get {
                return this.GiaField;
            }
            set {
                if ((this.GiaField.Equals(value) != true)) {
                    this.GiaField = value;
                    this.RaisePropertyChanged("Gia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaPN {
            get {
                return this.MaPNField;
            }
            set {
                if ((this.MaPNField.Equals(value) != true)) {
                    this.MaPNField = value;
                    this.RaisePropertyChanged("MaPN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaSP {
            get {
                return this.MaSPField;
            }
            set {
                if ((this.MaSPField.Equals(value) != true)) {
                    this.MaSPField = value;
                    this.RaisePropertyChanged("MaSP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LapTopService.ServiceReferenceSanPham.PhieuNhap PhieuNhap {
            get {
                return this.PhieuNhapField;
            }
            set {
                if ((object.ReferenceEquals(this.PhieuNhapField, value) != true)) {
                    this.PhieuNhapField = value;
                    this.RaisePropertyChanged("PhieuNhap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LapTopService.ServiceReferenceSanPham.SanPham SanPham {
            get {
                return this.SanPhamField;
            }
            set {
                if ((object.ReferenceEquals(this.SanPhamField, value) != true)) {
                    this.SanPhamField = value;
                    this.RaisePropertyChanged("SanPham");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SoLuong {
            get {
                return this.SoLuongField;
            }
            set {
                if ((this.SoLuongField.Equals(value) != true)) {
                    this.SoLuongField = value;
                    this.RaisePropertyChanged("SoLuong");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DonHang", Namespace="http://schemas.datacontract.org/2004/07/WcfLapTopService")]
    [System.SerializableAttribute()]
    public partial class DonHang : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LapTopService.ServiceReferenceSanPham.CT_DonHang[] CT_DonHangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LapTopService.ServiceReferenceSanPham.KhachHang KhachHangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaDHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MaKHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MaNVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> NgayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LapTopService.ServiceReferenceSanPham.NhanVien NhanVienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TrangThaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TrigiaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LapTopService.ServiceReferenceSanPham.CT_DonHang[] CT_DonHang {
            get {
                return this.CT_DonHangField;
            }
            set {
                if ((object.ReferenceEquals(this.CT_DonHangField, value) != true)) {
                    this.CT_DonHangField = value;
                    this.RaisePropertyChanged("CT_DonHang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LapTopService.ServiceReferenceSanPham.KhachHang KhachHang {
            get {
                return this.KhachHangField;
            }
            set {
                if ((object.ReferenceEquals(this.KhachHangField, value) != true)) {
                    this.KhachHangField = value;
                    this.RaisePropertyChanged("KhachHang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaDH {
            get {
                return this.MaDHField;
            }
            set {
                if ((this.MaDHField.Equals(value) != true)) {
                    this.MaDHField = value;
                    this.RaisePropertyChanged("MaDH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MaKH {
            get {
                return this.MaKHField;
            }
            set {
                if ((this.MaKHField.Equals(value) != true)) {
                    this.MaKHField = value;
                    this.RaisePropertyChanged("MaKH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MaNV {
            get {
                return this.MaNVField;
            }
            set {
                if ((this.MaNVField.Equals(value) != true)) {
                    this.MaNVField = value;
                    this.RaisePropertyChanged("MaNV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Ngay {
            get {
                return this.NgayField;
            }
            set {
                if ((this.NgayField.Equals(value) != true)) {
                    this.NgayField = value;
                    this.RaisePropertyChanged("Ngay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LapTopService.ServiceReferenceSanPham.NhanVien NhanVien {
            get {
                return this.NhanVienField;
            }
            set {
                if ((object.ReferenceEquals(this.NhanVienField, value) != true)) {
                    this.NhanVienField = value;
                    this.RaisePropertyChanged("NhanVien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TrangThai {
            get {
                return this.TrangThaiField;
            }
            set {
                if ((this.TrangThaiField.Equals(value) != true)) {
                    this.TrangThaiField = value;
                    this.RaisePropertyChanged("TrangThai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Trigia {
            get {
                return this.TrigiaField;
            }
            set {
                if ((this.TrigiaField.Equals(value) != true)) {
                    this.TrigiaField = value;
                    this.RaisePropertyChanged("Trigia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KhachHang", Namespace="http://schemas.datacontract.org/2004/07/WcfLapTopService")]
    [System.SerializableAttribute()]
    public partial class KhachHang : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiaChiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DienThoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LapTopService.ServiceReferenceSanPham.DonHang[] DonHangsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GioiTinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoTenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaKHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> NgaySinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiaChi {
            get {
                return this.DiaChiField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaChiField, value) != true)) {
                    this.DiaChiField = value;
                    this.RaisePropertyChanged("DiaChi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DienThoai {
            get {
                return this.DienThoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.DienThoaiField, value) != true)) {
                    this.DienThoaiField = value;
                    this.RaisePropertyChanged("DienThoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LapTopService.ServiceReferenceSanPham.DonHang[] DonHangs {
            get {
                return this.DonHangsField;
            }
            set {
                if ((object.ReferenceEquals(this.DonHangsField, value) != true)) {
                    this.DonHangsField = value;
                    this.RaisePropertyChanged("DonHangs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GioiTinh {
            get {
                return this.GioiTinhField;
            }
            set {
                if ((object.ReferenceEquals(this.GioiTinhField, value) != true)) {
                    this.GioiTinhField = value;
                    this.RaisePropertyChanged("GioiTinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HoTen {
            get {
                return this.HoTenField;
            }
            set {
                if ((object.ReferenceEquals(this.HoTenField, value) != true)) {
                    this.HoTenField = value;
                    this.RaisePropertyChanged("HoTen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaKH {
            get {
                return this.MaKHField;
            }
            set {
                if ((this.MaKHField.Equals(value) != true)) {
                    this.MaKHField = value;
                    this.RaisePropertyChanged("MaKH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> NgaySinh {
            get {
                return this.NgaySinhField;
            }
            set {
                if ((this.NgaySinhField.Equals(value) != true)) {
                    this.NgaySinhField = value;
                    this.RaisePropertyChanged("NgaySinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NhanVien", Namespace="http://schemas.datacontract.org/2004/07/WcfLapTopService")]
    [System.SerializableAttribute()]
    public partial class NhanVien : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LapTopService.ServiceReferenceSanPham.DonHang[] DonHangsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaNVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LapTopService.ServiceReferenceSanPham.PhanQuyen PhanQuyenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LapTopService.ServiceReferenceSanPham.PhieuNhap[] PhieuNhapsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuyenNVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenNVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LapTopService.ServiceReferenceSanPham.DonHang[] DonHangs {
            get {
                return this.DonHangsField;
            }
            set {
                if ((object.ReferenceEquals(this.DonHangsField, value) != true)) {
                    this.DonHangsField = value;
                    this.RaisePropertyChanged("DonHangs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaNV {
            get {
                return this.MaNVField;
            }
            set {
                if ((this.MaNVField.Equals(value) != true)) {
                    this.MaNVField = value;
                    this.RaisePropertyChanged("MaNV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LapTopService.ServiceReferenceSanPham.PhanQuyen PhanQuyen {
            get {
                return this.PhanQuyenField;
            }
            set {
                if ((object.ReferenceEquals(this.PhanQuyenField, value) != true)) {
                    this.PhanQuyenField = value;
                    this.RaisePropertyChanged("PhanQuyen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LapTopService.ServiceReferenceSanPham.PhieuNhap[] PhieuNhaps {
            get {
                return this.PhieuNhapsField;
            }
            set {
                if ((object.ReferenceEquals(this.PhieuNhapsField, value) != true)) {
                    this.PhieuNhapsField = value;
                    this.RaisePropertyChanged("PhieuNhaps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuyenNV {
            get {
                return this.QuyenNVField;
            }
            set {
                if ((this.QuyenNVField.Equals(value) != true)) {
                    this.QuyenNVField = value;
                    this.RaisePropertyChanged("QuyenNV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenNV {
            get {
                return this.TenNVField;
            }
            set {
                if ((object.ReferenceEquals(this.TenNVField, value) != true)) {
                    this.TenNVField = value;
                    this.RaisePropertyChanged("TenNV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhanQuyen", Namespace="http://schemas.datacontract.org/2004/07/WcfLapTopService")]
    [System.SerializableAttribute()]
    public partial class PhanQuyen : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaPQField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LapTopService.ServiceReferenceSanPham.NhanVien[] NhanViensField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenPQField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaPQ {
            get {
                return this.MaPQField;
            }
            set {
                if ((this.MaPQField.Equals(value) != true)) {
                    this.MaPQField = value;
                    this.RaisePropertyChanged("MaPQ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LapTopService.ServiceReferenceSanPham.NhanVien[] NhanViens {
            get {
                return this.NhanViensField;
            }
            set {
                if ((object.ReferenceEquals(this.NhanViensField, value) != true)) {
                    this.NhanViensField = value;
                    this.RaisePropertyChanged("NhanViens");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenPQ {
            get {
                return this.TenPQField;
            }
            set {
                if ((object.ReferenceEquals(this.TenPQField, value) != true)) {
                    this.TenPQField = value;
                    this.RaisePropertyChanged("TenPQ");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhieuNhap", Namespace="http://schemas.datacontract.org/2004/07/WcfLapTopService")]
    [System.SerializableAttribute()]
    public partial class PhieuNhap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LapTopService.ServiceReferenceSanPham.CT_PhieuNhap[] CT_PhieuNhapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MaNCCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MaNVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaPNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> NgayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LapTopService.ServiceReferenceSanPham.NhaCungCap NhaCungCapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LapTopService.ServiceReferenceSanPham.NhanVien NhanVienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TrigiaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LapTopService.ServiceReferenceSanPham.CT_PhieuNhap[] CT_PhieuNhap {
            get {
                return this.CT_PhieuNhapField;
            }
            set {
                if ((object.ReferenceEquals(this.CT_PhieuNhapField, value) != true)) {
                    this.CT_PhieuNhapField = value;
                    this.RaisePropertyChanged("CT_PhieuNhap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MaNCC {
            get {
                return this.MaNCCField;
            }
            set {
                if ((this.MaNCCField.Equals(value) != true)) {
                    this.MaNCCField = value;
                    this.RaisePropertyChanged("MaNCC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MaNV {
            get {
                return this.MaNVField;
            }
            set {
                if ((this.MaNVField.Equals(value) != true)) {
                    this.MaNVField = value;
                    this.RaisePropertyChanged("MaNV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaPN {
            get {
                return this.MaPNField;
            }
            set {
                if ((this.MaPNField.Equals(value) != true)) {
                    this.MaPNField = value;
                    this.RaisePropertyChanged("MaPN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Ngay {
            get {
                return this.NgayField;
            }
            set {
                if ((this.NgayField.Equals(value) != true)) {
                    this.NgayField = value;
                    this.RaisePropertyChanged("Ngay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LapTopService.ServiceReferenceSanPham.NhaCungCap NhaCungCap {
            get {
                return this.NhaCungCapField;
            }
            set {
                if ((object.ReferenceEquals(this.NhaCungCapField, value) != true)) {
                    this.NhaCungCapField = value;
                    this.RaisePropertyChanged("NhaCungCap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LapTopService.ServiceReferenceSanPham.NhanVien NhanVien {
            get {
                return this.NhanVienField;
            }
            set {
                if ((object.ReferenceEquals(this.NhanVienField, value) != true)) {
                    this.NhanVienField = value;
                    this.RaisePropertyChanged("NhanVien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Trigia {
            get {
                return this.TrigiaField;
            }
            set {
                if ((this.TrigiaField.Equals(value) != true)) {
                    this.TrigiaField = value;
                    this.RaisePropertyChanged("Trigia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NhaCungCap", Namespace="http://schemas.datacontract.org/2004/07/WcfLapTopService")]
    [System.SerializableAttribute()]
    public partial class NhaCungCap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiaChiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaNCCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LapTopService.ServiceReferenceSanPham.PhieuNhap[] PhieuNhapsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoDTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenNCCField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiaChi {
            get {
                return this.DiaChiField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaChiField, value) != true)) {
                    this.DiaChiField = value;
                    this.RaisePropertyChanged("DiaChi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaNCC {
            get {
                return this.MaNCCField;
            }
            set {
                if ((this.MaNCCField.Equals(value) != true)) {
                    this.MaNCCField = value;
                    this.RaisePropertyChanged("MaNCC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LapTopService.ServiceReferenceSanPham.PhieuNhap[] PhieuNhaps {
            get {
                return this.PhieuNhapsField;
            }
            set {
                if ((object.ReferenceEquals(this.PhieuNhapsField, value) != true)) {
                    this.PhieuNhapsField = value;
                    this.RaisePropertyChanged("PhieuNhaps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SoDT {
            get {
                return this.SoDTField;
            }
            set {
                if ((object.ReferenceEquals(this.SoDTField, value) != true)) {
                    this.SoDTField = value;
                    this.RaisePropertyChanged("SoDT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenNCC {
            get {
                return this.TenNCCField;
            }
            set {
                if ((object.ReferenceEquals(this.TenNCCField, value) != true)) {
                    this.TenNCCField = value;
                    this.RaisePropertyChanged("TenNCC");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceSanPham.IServiceSanPham")]
    public interface IServiceSanPham {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSanPham/SelectSanPham", ReplyAction="http://tempuri.org/IServiceSanPham/SelectSanPhamResponse")]
        LapTopService.ServiceReferenceSanPham.SanPham[] SelectSanPham();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSanPham/SelectSanPham", ReplyAction="http://tempuri.org/IServiceSanPham/SelectSanPhamResponse")]
        System.Threading.Tasks.Task<LapTopService.ServiceReferenceSanPham.SanPham[]> SelectSanPhamAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSanPham/SelectSanPhamTheoPhanLoai", ReplyAction="http://tempuri.org/IServiceSanPham/SelectSanPhamTheoPhanLoaiResponse")]
        LapTopService.ServiceReferenceSanPham.SanPham[] SelectSanPhamTheoPhanLoai(int loai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSanPham/SelectSanPhamTheoPhanLoai", ReplyAction="http://tempuri.org/IServiceSanPham/SelectSanPhamTheoPhanLoaiResponse")]
        System.Threading.Tasks.Task<LapTopService.ServiceReferenceSanPham.SanPham[]> SelectSanPhamTheoPhanLoaiAsync(int loai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSanPham/InsertSanPham", ReplyAction="http://tempuri.org/IServiceSanPham/InsertSanPhamResponse")]
        int InsertSanPham(LapTopService.ServiceReferenceSanPham.SanPham info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSanPham/InsertSanPham", ReplyAction="http://tempuri.org/IServiceSanPham/InsertSanPhamResponse")]
        System.Threading.Tasks.Task<int> InsertSanPhamAsync(LapTopService.ServiceReferenceSanPham.SanPham info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSanPham/UpdateSanPham", ReplyAction="http://tempuri.org/IServiceSanPham/UpdateSanPhamResponse")]
        int UpdateSanPham(LapTopService.ServiceReferenceSanPham.SanPham info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSanPham/UpdateSanPham", ReplyAction="http://tempuri.org/IServiceSanPham/UpdateSanPhamResponse")]
        System.Threading.Tasks.Task<int> UpdateSanPhamAsync(LapTopService.ServiceReferenceSanPham.SanPham info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSanPham/DeleteSanPham", ReplyAction="http://tempuri.org/IServiceSanPham/DeleteSanPhamResponse")]
        int DeleteSanPham(LapTopService.ServiceReferenceSanPham.SanPham info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSanPham/DeleteSanPham", ReplyAction="http://tempuri.org/IServiceSanPham/DeleteSanPhamResponse")]
        System.Threading.Tasks.Task<int> DeleteSanPhamAsync(LapTopService.ServiceReferenceSanPham.SanPham info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSanPham/SelectSanPhamByCategory", ReplyAction="http://tempuri.org/IServiceSanPham/SelectSanPhamByCategoryResponse")]
        LapTopService.ServiceReferenceSanPham.SanPham[] SelectSanPhamByCategory(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSanPham/SelectSanPhamByCategory", ReplyAction="http://tempuri.org/IServiceSanPham/SelectSanPhamByCategoryResponse")]
        System.Threading.Tasks.Task<LapTopService.ServiceReferenceSanPham.SanPham[]> SelectSanPhamByCategoryAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSanPham/ChitietSanPham", ReplyAction="http://tempuri.org/IServiceSanPham/ChitietSanPhamResponse")]
        LapTopService.ServiceReferenceSanPham.SanPham[] ChitietSanPham(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSanPham/ChitietSanPham", ReplyAction="http://tempuri.org/IServiceSanPham/ChitietSanPhamResponse")]
        System.Threading.Tasks.Task<LapTopService.ServiceReferenceSanPham.SanPham[]> ChitietSanPhamAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSanPham/SearchSanPham", ReplyAction="http://tempuri.org/IServiceSanPham/SearchSanPhamResponse")]
        LapTopService.ServiceReferenceSanPham.SanPham[] SearchSanPham(int nhasanxuat, string Str_giatu, string Str_den);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSanPham/SearchSanPham", ReplyAction="http://tempuri.org/IServiceSanPham/SearchSanPhamResponse")]
        System.Threading.Tasks.Task<LapTopService.ServiceReferenceSanPham.SanPham[]> SearchSanPhamAsync(int nhasanxuat, string Str_giatu, string Str_den);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceSanPhamChannel : LapTopService.ServiceReferenceSanPham.IServiceSanPham, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSanPhamClient : System.ServiceModel.ClientBase<LapTopService.ServiceReferenceSanPham.IServiceSanPham>, LapTopService.ServiceReferenceSanPham.IServiceSanPham {
        
        public ServiceSanPhamClient() {
        }
        
        public ServiceSanPhamClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSanPhamClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSanPhamClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSanPhamClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LapTopService.ServiceReferenceSanPham.SanPham[] SelectSanPham() {
            return base.Channel.SelectSanPham();
        }
        
        public System.Threading.Tasks.Task<LapTopService.ServiceReferenceSanPham.SanPham[]> SelectSanPhamAsync() {
            return base.Channel.SelectSanPhamAsync();
        }
        
        public LapTopService.ServiceReferenceSanPham.SanPham[] SelectSanPhamTheoPhanLoai(int loai) {
            return base.Channel.SelectSanPhamTheoPhanLoai(loai);
        }
        
        public System.Threading.Tasks.Task<LapTopService.ServiceReferenceSanPham.SanPham[]> SelectSanPhamTheoPhanLoaiAsync(int loai) {
            return base.Channel.SelectSanPhamTheoPhanLoaiAsync(loai);
        }
        
        public int InsertSanPham(LapTopService.ServiceReferenceSanPham.SanPham info) {
            return base.Channel.InsertSanPham(info);
        }
        
        public System.Threading.Tasks.Task<int> InsertSanPhamAsync(LapTopService.ServiceReferenceSanPham.SanPham info) {
            return base.Channel.InsertSanPhamAsync(info);
        }
        
        public int UpdateSanPham(LapTopService.ServiceReferenceSanPham.SanPham info) {
            return base.Channel.UpdateSanPham(info);
        }
        
        public System.Threading.Tasks.Task<int> UpdateSanPhamAsync(LapTopService.ServiceReferenceSanPham.SanPham info) {
            return base.Channel.UpdateSanPhamAsync(info);
        }
        
        public int DeleteSanPham(LapTopService.ServiceReferenceSanPham.SanPham info) {
            return base.Channel.DeleteSanPham(info);
        }
        
        public System.Threading.Tasks.Task<int> DeleteSanPhamAsync(LapTopService.ServiceReferenceSanPham.SanPham info) {
            return base.Channel.DeleteSanPhamAsync(info);
        }
        
        public LapTopService.ServiceReferenceSanPham.SanPham[] SelectSanPhamByCategory(int id) {
            return base.Channel.SelectSanPhamByCategory(id);
        }
        
        public System.Threading.Tasks.Task<LapTopService.ServiceReferenceSanPham.SanPham[]> SelectSanPhamByCategoryAsync(int id) {
            return base.Channel.SelectSanPhamByCategoryAsync(id);
        }
        
        public LapTopService.ServiceReferenceSanPham.SanPham[] ChitietSanPham(int id) {
            return base.Channel.ChitietSanPham(id);
        }
        
        public System.Threading.Tasks.Task<LapTopService.ServiceReferenceSanPham.SanPham[]> ChitietSanPhamAsync(int id) {
            return base.Channel.ChitietSanPhamAsync(id);
        }
        
        public LapTopService.ServiceReferenceSanPham.SanPham[] SearchSanPham(int nhasanxuat, string Str_giatu, string Str_den) {
            return base.Channel.SearchSanPham(nhasanxuat, Str_giatu, Str_den);
        }
        
        public System.Threading.Tasks.Task<LapTopService.ServiceReferenceSanPham.SanPham[]> SearchSanPhamAsync(int nhasanxuat, string Str_giatu, string Str_den) {
            return base.Channel.SearchSanPhamAsync(nhasanxuat, Str_giatu, Str_den);
        }
    }
}
